# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zustellung',
            name='hausnummer',
            field=models.IntegerField(unique=True),
        ),
    ]
