# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170718_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zustellung',
            name='hausnummer',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='zustellung',
            unique_together=set([('hausnummer', 'strasse')]),
        ),
    ]
