# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170718_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='titel',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='strasse',
            name='strassenname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zusatzinformation',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zusatzinformation',
            name='bild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Bild'),
        ),
    ]
