# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170718_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zusatzinformation',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zusatzinformation',
            name='bild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Bild'),
        ),
    ]
