# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170718_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zusatzinformation',
            name='zustellung',
        ),
        migrations.AddField(
            model_name='zustellung',
            name='zusatzinformation',
            field=models.ManyToManyField(to='website.Zusatzinformation'),
        ),
    ]
