# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170718_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zustellung',
            old_name='zusatzinformation',
            new_name='zusatzinformationen',
        ),
    ]
