# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170718_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zustellung',
            name='zusatzinformationen',
            field=models.ManyToManyField(blank=True, to='website.Zusatzinformation'),
        ),
    ]
