# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170718_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bild',
            options={'ordering': ('titel',)},
        ),
        migrations.AlterModelOptions(
            name='strasse',
            options={'ordering': ('strassenname',)},
        ),
        migrations.AlterModelOptions(
            name='zusatzinformation',
            options={'ordering': ('beschreibung', 'information')},
        ),
        migrations.AlterModelOptions(
            name='zusatztext',
            options={'ordering': ('text',)},
        ),
    ]
