# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170718_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='datei',
            field=models.ImageField(upload_to=''),
        ),
    ]
