# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
