# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170718_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zustellung',
            options={'ordering': ('strasse', 'hausnummer', 'hausnummer_zusatz')},
        ),
        migrations.AddField(
            model_name='zustellung',
            name='hausnummer_zusatz',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='zustellung',
            unique_together=set([('hausnummer', 'strasse', 'hausnummer_zusatz')]),
        ),
    ]
